#!/bin/bash

#SBATCH --job-name=$JOBNAME
#SBATCH --cpus-per-task=2
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=8192

module load gcc/5.4.0
module load boost/1.67.0-gcc5
module load cplex/12.8.0
./remove_redundant_$DECOMPTYPE_constraints_script_XXXXX
